apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
    name: fluentd
spec:
    template:
        metadata:
            labels:
                app: fluentd
            name: fluentd
        spec:
            containers:
                - image: olblak/fluentd-k8s-azure:0.5.0
                  imagePullPolicy: Always
                  name: fluentd
                  env:
                    - name: AZURE_WORKSPACE_ID
                      valueFrom:
                        secretKeyRef:
                            name: azure-secret
                            key: azurelogsanalyticsworkspace
                    - name: AZURE_SHARED_KEY
                      valueFrom:
                        secretKeyRef: 
                            name: azure-secret
                            key: azurelogsstorageaccountkey
                  volumeMounts:
                      # Required if we want to write analyzed logs to /fluentd/log/dest
                      # - name: logs
                      # - mountPath: /fluentd/log/dest

                    - name: varlog
                      mountPath: /fluentd/log/source
                      readOnly: true

                    - name: varlibdockercontainers
                      mountPath: /var/lib/docker/containers
                      readOnly: true

            volumes:
                # Required if we want to mount a shared disk storage
                #     - name: logs
                #       azureFile: 
                #         secretName: azure-secret
                #         shareName: logs
                #         readOnly: false

                - name: varlibdockercontainers
                  hostPath:
                      path: /var/lib/docker/containers

                - name: varlog
                  hostPath:
                      path: /var/log
