apiVersion: v1
kind: Secret
metadata:
  name: azure-secret
type: Opaque
data:
  azurestorageaccountname: `echo -n "$STORAGE_ACCOUNT_NAME"| base64`
  azurestorageaccountkey: `echo -n "$STORAGE_ACCOUNT_KEY" | base64`
  azurelogsstorageaccountkey: `echo -n "$STORAGE_ACCOUNT_LOGS_KEY"| base64`
  azurelogsanalyticsworkspace: `echo -n "$AZURE_OMS_CUSTOMER_ID"`| base64

# How to get storage account key 
# PREFIX=<env_prefix defined by terraform plans> 
# STORAGE_ACCOUNT_KEY=`az storage account keys list -n "${PREFIX}logs" -g "${PREFIX}logs" -o json --query 'keys[0].value'`
# STORAGE_ACCOUNT_NAME=`az storage account show -g "${PREFIX}logs" -n "${PREFIX}logs" -o json --query name`
# AZURE_OMS_CUSTOMER_ID=`az resource  show --resource-type Microsoft.OperationalInsights/workspaces --resource-group ${PREFIX}logs -n ${PREFIX}logs -o jsonc  --query properties.customerId
# `
#
# We can use following secret to mount azure_file
#  		volumes:
# 			- name: logs
#        	  azureFile: 
#         		secretName: azure-secret
#        		shareName: logs
#           	readOnly: false
